version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
    rs-lng:
        image: "naturalis/rs-lng:8.6"
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-resourcespace}
            MYSQL_USER: ${MYSQL_USER:-henk}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-henk}
        logging: *default-logging
        ports:
            - "${WEB_EXTERNAL_PORT:-8080}:80"
        volumes:
            - ${BASE_PATH:-/data}/www:/var/www/
            - ${BASE_PATH:-/data}/log/apache2:/var/log/apache2
        labels:
            - "traefik.backend=naturalis-rs"
            - "traefik.enable=true"
            - "traefik.port=80"
            - "${SITE_URL:-traefik.frontend.rule=Host:rs-test.naturalis.nl}"
        networks:
            - default

    db:
        image: "mysql:5.7"
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-resourcespace}
            MYSQL_USER: ${MYSQL_USER:-henk}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-henk}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-henk}
        logging: *default-logging
        networks:
            - default
        ports:
            - "${MYSQL_EXTERNAL_PORT:-3306}:3306"
        volumes:
            - ${BASE_PATH:-/data}/mysql/db:/var/lib/mysql
            - ${BASE_PATH:-/data}/log/mysql:/var/log/mysql
            - ${BASE_PATH:-/data}/mysql/dump:/tmp
        healthcheck:
            test: mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e 'connect ${MYSQL_DATABASE:-resourcespace}'

    traefik:
        image: traefik:1.7.12
        container_name: traefik
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
            - 8081:8080
        networks:
            - default
            - web
        logging: *default-logging
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${TRAEFIK_TOML_FILE:-./traefik.toml}:/traefik.toml
            - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt

networks:
    default:
    web:
        external: true
